# Generated by Django 3.0.5 on 2020-04-25 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('link', models.URLField(max_length=100)),
                ('itemOrder', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['itemOrder'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('name', models.CharField(max_length=75, primary_key=True, serialize=False)),
                ('address_line1', models.CharField(blank=True, max_length=45, null=True, verbose_name='Address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=45, null=True, verbose_name='Address line 2')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal Code')),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('online', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stockist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/stockists')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Venue')),
            ],
        ),
    ]
