# Generated by Django 3.0.5 on 2020-05-09 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200425_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockist',
            options={'ordering': ['-end_date']},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name']},
        ),
    ]
