# Generated by Django 3.0.5 on 2020-04-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=35, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('image', models.ImageField(upload_to='img/gallery')),
                ('title', models.CharField(max_length=75, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('archive', models.BooleanField()),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('categories', models.ManyToManyField(related_name='photos', to='gallery.Category')),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
    ]
