# Generated by Django 3.0.6 on 2020-05-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20200510_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='artists_selection',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
