# Generated by Django 3.0.5 on 2020-04-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('subject', models.CharField(max_length=75, primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='img/announcement')),
                ('link', models.URLField(max_length=100)),
                ('publish_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SlideShowItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='img/slideshowIndex')),
                ('itemOrder', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['itemOrder'],
            },
        ),
    ]
